version: '3'

services:
  dev:
    build: support/dev
    working_dir: /app
    volumes:
      - .:/app
      - ruby-gem-cache:/usr/local/bundle
    entrypoint: ["sh", "-c"]

volumes:
  ruby-gem-cache:
    external: true
