#!/bin/bash -e
cd $(dirname $0)/..

REPOSITORY='94xychen/sub2conf'
TAG="${TAG_PREFIX}$(date +%Y%m%d%H%M%S)"
IMAGE="${REPOSITORY}:${TAG}"

${BUILD_CMD} build -t ${IMAGE} --build-arg BASE_IMAGE=${BASE_IMAGE} --build-arg ARCH=${ARCH} ${BUILD_PRAMETERS} .

docker push ${IMAGE}

LATEST_TAG="${TAG_PREFIX}latest"
IMAGE_LATEST=${REPOSITORY}:${LATEST_TAG}
docker tag ${IMAGE} ${IMAGE_LATEST}

docker push ${IMAGE_LATEST}

echo "${IMAGE}" | tee .artifacts.txt
