#!/bin/bash -e
cd $(dirname $0)/..

REPOSITORY='94xychen/sub2conf'
TAG="$(date +%Y%m%d%H%M%S)"
IMAGE="${REPOSITORY}:${TAG}"

docker buildx build --tag ${IMAGE} --push --platform linux/arm/v7,linux/amd64,linux/arm64/v8 .

echo "${IMAGE}" | tee .artifacts.txt
