#!/bin/bash -ex

cd $(dirname $0)/..

REPOSITORY=94xychen/sub2conf
TAG=$(date +%Y%m%d%H%M%S)

# for X86

# IMAGE=${REPOSITORY}:${TAG}
# docker build -t ${IMAGE} --build-arg BASE_IMAGE=ruby:alpine --build-arg ARCH=linux64 .

# docker push ${IMAGE}


# IMAGE_LATEST=${REPOSITORY}:latest

# docker tag ${IMAGE} ${IMAGE_LATEST}
# docker push ${IMAGE_LATEST}

# for arm v7

IMAGE=${REPOSITORY}:arm-v7-${TAG}

docker buildx build --platform linux/arm/v7 -t ${IMAGE} --build-arg ARCH=armhf --build-arg BASE_IMAGE=arm32v7/ruby:alpine .

docker images

docker push ${IMAGE}

IMAGE_LATEST=${REPOSITORY}:arm-v7-latest

docker tag ${IMAGE} ${IMAGE_LATEST}

docker push ${IMAGE_LATEST}
