name: CI
on:
  push:
  workflow_dispatch:
env:
  CI: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: release
        run: auto/release
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: .artifacts.txt
  security-check:
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download artifacts
        uses: actions/download-artifact@v2
      - name: prepare for the artifacts
        run: cat images/.artifacts.txt > .artifacts.txt
      - name: scan images
        run: auto/image-scan
